#!/bin/bash

run_tty=`tty`

# 第一引数で指定された拡張子の画像ファイルを監視し、
# 変更があれば画像表示コマンドを実行する設定ファイルを作成。
GOEMON_FILE=" # Generated by sixelPreview.sh
tasks:
- match: '*.${1}'
  commands:
      - printImg.sh \${GOEMON_TARGET_FILE} ${run_tty}
"

# goemon 設定ファイル作成
cat <<< "${GOEMON_FILE}" > ./goemon.yml

# goemon 起動
goemon -- 2> /dev/null &

# preview 用 bash の起動
PS1="" /bin/bash --norc

# goemon 停止
killall goemon

# goemon 設定ファイル削除
rm goemon.yml
